### ISSUE TITLE
Brainweb-single_slice_motion problems

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#48] opened 2020-06-04 09:53 UTC
Images loaded look like this
![image](https://user-images.githubusercontent.com/6362141/83742214-0f735580-a651-11ea-9a81-b6d458e43b32.png)
Motion states and sinos look empty.

It uses `resampler.process` which in this case should be replaced by `forward`

**Comment by KrisThielemans** [comment] 2020-06-04 09:58
same for `Brainweb` notebook

**Comment by rijobro** [comment] 2020-06-04 10:05
@casperdcl is this related to https://github.com/casperdcl/brainweb/issues/1?

**Comment by casperdcl** [comment] 2020-06-04 10:09
:eyes: looks like it; never been able to reproduce this - would be great if you can. Are you running this on windows?

**Comment by KrisThielemans** [comment] 2020-06-04 10:11
This is on our new VM (ubuntu 18.04, but python 2).
https://zenodo.org/record/3874226#.XtgnuGhKh6o

**Comment by casperdcl** [comment] 2020-06-04 10:24
Ooh nice. Will try to reproduce... Which ova? 2.0, 2.1, or 2.2-rc.1?

**Comment by KrisThielemans** [comment] 2020-06-04 10:25
2.2-rc.1. I'm not sure what happens with the previous ones (but should have been fine)

**Comment by rijobro** [comment] 2020-06-04 10:41
Blank with python2, normal with python3 if that helps narrow things down for you.

**Comment by casperdcl** [comment] 2020-06-04 12:41
fixed in `brainweb>=1.5.1`

**Comment by rijobro** [comment] 2020-06-04 14:08
Sure?

![image](https://user-images.githubusercontent.com/33289025/83767143-2a57c100-a675-11ea-899d-7eec2b8dba04.png)

![image](https://user-images.githubusercontent.com/33289025/83767166-33e12900-a675-11ea-8184-623a1dc9f059.png)

**Comment by rijobro** [comment] 2020-06-04 14:10
ah, it was reusing pre-downloaded data. deleted the working folder and it seems to be working.

**Closed** 2020-06-04 14:25 UTC
Labels: bug, invalid
